### ISSUE TITLE
Comparison to zero throws error

### ISSUE THREAD

**Issue by nasser** [swannodette/cljs-bootstrap#3]
```
cljs-bootstrap.repl> (< 10 2)
false
cljs-bootstrap.repl> (< 10 0)
Error
    at new cljs$core$ExceptionInfo (/Users/nasser/Scratch/cljs/repl-all.js:33197:11)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/Users/nasser/Scratch/cljs/repl-all.js:33238:10)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/Users/nasser/Scratch/cljs/repl-all.js:33235:28)
    at cljs$core$ex_info (/Users/nasser/Scratch/cljs/repl-all.js:33225:32)
    at Function.cljs.tools.reader.reader_types.reader_error.cljs$core$IFn$_invoke$arity$variadic (/Users/nasser/Scratch/cljs/repl-all.js:34775:27)
    at cljs$tools$reader$reader_types$reader_error (/Users/nasser/Scratch/cljs/repl-all.js:34772:54)
    at cljs$tools$reader$read_number (/Users/nasser/Scratch/cljs/repl-all.js:35438:60)
    at /Users/nasser/Scratch/cljs/repl-all.js:36447:56
    at cljs$tools$reader$reader_types$log_source (/Users/nasser/Scratch/cljs/repl-all.js:34843:20)
    at cljs$tools$reader$target (/Users/nasser/Scratch/cljs/repl-all.js:36426:56)
cljs-bootstrap.repl> (> 10 1)
true
cljs-bootstrap.repl> (> 10 0)
Error
    at new cljs$core$ExceptionInfo (/Users/nasser/Scratch/cljs/repl-all.js:33197:11)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/Users/nasser/Scratch/cljs/repl-all.js:33238:10)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/Users/nasser/Scratch/cljs/repl-all.js:33235:28)
    at cljs$core$ex_info (/Users/nasser/Scratch/cljs/repl-all.js:33225:32)
    at Function.cljs.tools.reader.reader_types.reader_error.cljs$core$IFn$_invoke$arity$variadic (/Users/nasser/Scratch/cljs/repl-all.js:34775:27)
    at cljs$tools$reader$reader_types$reader_error (/Users/nasser/Scratch/cljs/repl-all.js:34772:54)
    at cljs$tools$reader$read_number (/Users/nasser/Scratch/cljs/repl-all.js:35438:60)
    at /Users/nasser/Scratch/cljs/repl-all.js:36447:56
    at cljs$tools$reader$reader_types$log_source (/Users/nasser/Scratch/cljs/repl-all.js:34843:20)
    at cljs$tools$reader$target (/Users/nasser/Scratch/cljs/repl-all.js:36426:56)
```

**Comment by kanaka** [comment]
I think it's just "0" by itself that causes the issue.

**Comment by nasser** [comment]
Oh, so it does!

**Comment by swannodette** [comment]
Can't reproduce this and far as I know Mike Fikes fixed it by fixing his build script.
